# Generated by Django 4.1.7 on 2023-02-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='Comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
