# Generated by Django 4.1.7 on 2023-02-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0002_vacation_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacation',
            old_name='Comments',
            new_name='comments',
        ),
    ]
